"""testing

Revision ID: 287380a40abd
Revises: 445428113c13
Create Date: 2019-03-19 16:35:58.864680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287380a40abd'
down_revision = '445428113c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yarn', sa.Column('skeinweight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yarn', 'skeinweight')
    # ### end Alembic commands ###
